### ISSUE TITLE
HockeyApp is not referenced

### ISSUE THREAD

**Issue by akamud** [xamarin/app-crm#109]
When I clone the project I can't compile because HockeyApp is not installed. This is the error reported: `the type or namespace name 'HockeyApp' could not be found`.

Shouldn't this be in `packages.config`?

**Comment by xiaocnie** [comment]
<Reference Include="HockeyApp.Android">
      <HintPath>..\Components\hockeyappandroid-3.7.1.0\lib\android\HockeyApp.Android.dll</HintPath>
    </Reference>

**Comment by jsauvexamarin** [comment]
Since the Xamarin tools no longer require a Xamarin account to build, and because the Xamarin component store still requires authentication with a Xamarin account, the Xamarin Component restore process will always fail unless a Xamarin account is logged into Visual Studio or Xamarin Studio.

I corrected the build issues by simply replacing all Xamarin Component Store components with the equivalent NuGets (including HockeyApp), since nuget.org requires no authentication.
